[project]
name = "bwrappy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
 "click>=8.1.8",
 "pydantic>=2.11.2",
 "pyyaml>=6.0.2",
]
